version: '3.8'

services:
  app:
    build: .
    command: bundle exec ruby app.rb -p 4567 -o 0.0.0.0
    depends_on:
      - db
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_DATABASE: blog
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: db
    tty: true
    stdin_open: true
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
